// pipeline{
//     agent any
//     stages{
//         stage('SCM Checkout'){
//             steps{
//                 git 'https://github.com/thinkC/ansible-config-mgt-new'
//             }
//         }
//         stage('Execute Ansible'){
//             steps{
//                ansiblePlaybook colorized: true, credentialsId: 'privateKEY', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/uat', playbook: 'playbooks/site.yml'
//             }
//         }
//         stage('Cleanup Workspace'){
//             steps{
//                 cleanWs()
//             }
//         }
//     }
// }




pipeline {
    agent any

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }
    }
}