---
- name: Install mySQL and other dependencies
  become: true
  apt:
   name: ['mysql-server', 'python3-pip', 
'libmysqlclient-dev', 'python3-dev', 'python3-mysqldb']
   state: present
   update_cache: True
  

- name: ensure mysql is started and enabled
  become: true
  ansible.builtin.service:
     name: mysql
     state: started 
     enabled: yes

- name: create /var/lib/mysql/mysql.sock
  become: true
  ansible.builtin.file:
    path: /var/lib/mysql/mysql.sock
    state: touch

- name: Create Database
  become: true
  mysql_db: 
   name: tooling
   state: present

- name: Create Application DB user
  become: true
  mysql_user:
   name: webaccess
   password: sePret^i
   host: '172.31.49.60'
   priv: '*.*:ALL,GRANT'
   state: present

# - name: update /ect/my.cf for bind-address
#   become: true
#   template:
#     src: templates/my.cnf.j2
#     dest: /etc/mysql/mysql.conf.d/mysqld.cnf
#   notify: Restart mysql

- name: update /etc/my.cf for bind-address
  become: true
  ansible.builtin.copy:
   src: /home/ubuntu/ansible-config-mgt-new/downloads/my.cnf.j2
   dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  # notify: Restart mysql

- name: restart mysql
  become: true
  ansible.builtin.service:
     name: mysql
     state: started 

- import_tasks: configure-firewall.yml