# ---
# - hosts: all
#   name:  dynamic variables 
#   import_playbook: ../static-assignments/common.yml 
#   include: ../dynamic-assignments/env-vars.yml
#   tags:
#    - always
# - hosts: webservers
#   name: Webserver assignment
#   import_playbook: ../static-assignments/uat-webservers.yml

# - hosts: uat-mysqlserver
#   name: MySQL assignment
#   import_playbook: ../static-assignments/uat-mysqlserver.yml

# # - hosts: lb
# # - name: Loadbalancers assignment
# # - import_playbook: ../static-assignments/loadbalancers.yml
# #   when: load_balancer_is_required 


#****************new**************

---
- name: Import common file
  import_playbook: ../static-assignments/common.yml
  tags:
    - always
- name: Include env-var files
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always
# - name: Import database files
#   import_playbook: ../static-assignments/uat-mysqlserver.yml

# - name: Import webservers
#   import_playbook: ../static-assignments/uat-webservers.yml

- name: Import lb
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required