---
- name: Import common file
  import_playbook: ../static-assignments/common.yml
  tags:
    - always
- name: Include env-var files
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always
- name: Import database files
  import_playbook: ../static-assignments/uat-mysqlserver.yml

- name: Import webservers
  import_playbook: ../static-assignments/uat-webservers.yml

- name: Import lb
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required


